version: '3'

services:
  #frontend:
  #  build: ./frontend
  #  container_name: frontend
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - demo-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment: # db가 의존성에 포함되어 있어서 임시로 제작. .env 파일로 변경 예정
      - DB_URL=jdbc:mysql://db:3306/testdb
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - demo-network
    volumes:
      - C:/Users/joeun/Desktop/profile_images:/app/data/profile_images
      - C:/Users/joeun/Desktop/funding_image:/app/data/funding_image
      - C:/Users/joeun/Desktop/project_document:/app/data/project_document

  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - db_test:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - demo-network


  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - demo-network
    depends_on:
      #    - frontend
      - backend

networks:
  demo-network:
    driver: bridge

volumes:
  db_test: