version: '3'

services:
#  frontend:
#    image: nginx:alpine
#    container_name: frontend
#    volumes:
#      - ./frontend:/usr/share/nginx/html
#    ports:
#      - "3000:80"
#    networks:
#      - demo-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment: # db가 의존성에 포함되어 있어서 임시로 제작. .env 파일로 변경 예정
      - DB_URL=jdbc:mysql://db:3306/testdb
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - demo-network

  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - db_test:/var/lib/mysql
    networks:
      - demo-network


  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - demo-network
    depends_on:
      #- frontend
      - backend

networks:
  demo-network:
    driver: bridge

volumes:
  db_test: